/* Copyright 2018. Yak Works Group Licensed under the Apache License, Version 2.0 */
package foo
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
