# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: ShipYak Gradle Plugins
description: Plugin tools to automate CI versioning, releasing, tagging and publishing
author: Yak.Works
group: org.yakworks

github:
  fullName: yakworks/gradle-plugins # will try and pick this up based on checkout repo

bot:
  email: 9cibot@9ci.com
  sign_commits: true

vault:
  repo: 9ci/vault

version:
  # after release, will set version.properties back to snapshot=true
  set_snapshot: true

team:
  developers: ['basejump: Joshua Burnett']

release:
  # after release, will set version.properties back to snapshot=true or releasable=false
  reset_flag: true
  # changelog: CHANGELOG.md

# publish:
#   branch_regex: master|dev|release/.+

maven:
  #repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots

codenarc:
  toolVersion: 2.2.0
