/* Copyright 2018. Yak Works Group Licensed under the Apache License, Version 2.0 */
package foo
/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
