# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # docker image with python and mkdocs on it already as well, based on gradle:4.6-alpine
      - image: yakworks/builder:jdk8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-gradle-{{ checksum "build.gradle" }}

      - run:
          name: gradle check tests.
#          command: ./gradlew check --stacktrace
          command: echo "foo"

      - save_cache:
          paths:
            - /home/gradle # the https://hub.docker.com/_/gradle/ containter does wierd stuff for cache
            - ~/.m2
            - ~/.gradle
          key: v3-gradle-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: plugin/build/reports/tests/test/
          destination: test-reports/unit/

      - store_artifacts:
          path: plugin/build/reports/codenarc/
          destination: codenarc/

      - store_test_results:
          path: plugin/build/test-results


  # Not running yet, need to add in shipkit
  pubish-plugin:
    docker:
      - image: yakworks/builder:jdk8
    resource_class: 'medium+'

    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-gradle-{{ checksum "build.gradle" }}

      - run: make vault.decrypt
      - run: make git.config-bot-user
      - run: make ship.release
      # if it meets the criteria to be IS_RELEASABLE, this will bump version and tag release on github
      - run: make ship.version

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context # context with shared ENV vars
      - pubish-plugin:
          context: bot-context
          requires: [build]
          filters: { branches: { only: [ master, /release\/.*/ ] } }
