# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: ShipYak Gradle Plugins
description: Plugin tools to automate CI versioning, releasing, tagging and publishing
author: 9ci Inc
group: org.yakworks

#github:
#  fullName: basejump/gorm-tools # will try and pick this up based on checkout repo

team:
  developers: ['basejump: Joshua Burnett']

releaseNotes:
  file: docs/release-notes.md
  publicationRepository: https://plugins.gradle.org/plugin/yakworks.shipyak

bintray:
  enabled: false

maven:
  #repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots

spotless:
  licenseHeader: |
    ${'/*\n* Copyright \$YEAR. ' + config.author + '. Licensed under the Apache License, Version 2.0 (the "License")\n' +
    '* You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0\n' +
    '*/'
    }
