/* Copyright 2019. 9ci Inc. Licensed under the Apache License, Version 2.0 */
package foo

import groovy.transform.CompileStatic

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
@CompileStatic
class Library {
    boolean someLibraryMethod() {
        true
    }
}
