# gradle project properties will get set on the project or the project.ext depending on whether they exist already or not
# the initial properties here will end up being set directly as gradle propeties just as they are in
title: # short desc used for docs
description: # REQUIRED
author: 9ci Inc # REQUIRED author for docs and copyright, used in licenseHeader too. Can be legal Org name or user name
license: Apache-2.0 # REQUIRED will be used in the docs, pom and bintray upload
# the pointer to the docs for this project
websiteUrl: ${"https://" + config.github.owner + ".github.io/" + config.github.repo} # default: "https://\${github.owner}.github.io/\${github.repo}"

# ---
# everything after the first separator will in the project.config

git:
  releasableBranchRegex: 'master|release/.+'   # matches 'master', 'release/2.x', 'release/3.x', etc.
  tagPrefix: v # so that tags are "v1.0", "v2.3.4"
  commitMessagePostfix: '[ci skip]'
  # config so it shows the user in the commits
  config:
    user: 9cibot
    email: <9cibot@9ci.com>

github:
  fullName: joedevs/my-lib # <Required> if set then this will take precedence. will concatenate owner/repo if empty.
  # owner and repo will be parsed from fullName or used to build fullname with repo depending on which on is set.
  owner: ${config.github.fullName.split('/')[0]} # joedevs
  repo: ${config.github.fullName.split('/')[1]} # my-lib
  issuesUrl: ${'https://github.com/' + config.github.repo + '/issues'} # defaults to : "https://github.com/\${github.repo}/issues"
  # token used for dry run and test builds so devs dont need a write token to get started
  writeAuthToken: '${System.getenv("GRGIT_USER") ?: System.getenv("GH_WRITE_TOKEN") ?: project.findProperty("gitHubToken") ?: "e7fe8fcdd6ffed5c38498c4c79b2a68e6f6ed1bb"}'
  readOnlyAuthToken: '${System.getenv("GRGIT_USER") ?: System.getenv("GH_WRITE_TOKEN") ?: project.findProperty("gitHubToken")}'

team:
  # keys here should be github user and name should match github name.
  developers: # REQUIRED ex: { basejump: Joshua Burnett,  }
  contributors:
  ignoredContributors: { 9cibot: 9ci Build Bot}

releaseNotes:
  file: docs/release-notes.md

# see docs here https://github.com/bintray/gradle-bintray-plugin. the yml support options are below
# this gets setup for each publishable project
bintray:
  enable: true # set this to false to turn off
  user: '${System.getenv("BINTRAY_USER") ?: project.findProperty("bintrayUser")}' # REQUIRED
  key: '${System.getenv("BINTRAY_KEY") ?: project.findProperty("bintrayKey")}' # REQUIRED
  pkg:
    repo: # REQUIRED
    userOrg: # REQUIRED
    name: # this will get set from each subprojects name during runtime
    websiteUrl: \${config.websiteUrl}
    issueTrackerUrl: \${config.github.issuesUrl}
    vcsUrl: \${config.github.vcsUrl}
    licenses: [ '${config.license}' ]
    publicDownloadNumbers: true
    version:
        name: ${project.version}
        mavenCentralSync:
          sync: false

maven:
  repoUrl:
  snapshotUrl: # set this when not publishing to an artifactory vs bintray and you have a different repo than the primary repoUrl

versions:
  hibernate: 5.2.16.Final
  buildTestData: 3.3.+
  views: 1.2.7

