# Can contain standard yaml pointers using the & and * and
# strings can also use GString syntax is it starts with $.
# available bound properties are this `config` and `project`.
# Helper methods are property(prop), findProperty(prop)
# and findAnyProperty(prop) which looks in env and system.properties.

title: # short title used for javadocs and documentation
description: # REQUIRED
author: 9ci Inc # REQUIRED author for docs, copyright, and spotless licenseHeader too. Can be legal Org name or user name
license: &License Apache-2.0 # REQUIRED will be used in the docs, pom
# the pointer to the docs for this project
websiteUrl: &SiteUrl ${"https://" + config.project.owner + ".github.io/" + config.project.repo}

# everything before the first separator will get set on the project property
# or project.ext and standards for gradle.properties should be followed.
# everything after the first separator will in the project.config

git:
  releasableBranchRegex: 'master|release/.+'   # matches 'master', 'release/2.x', 'release/3.x', etc.
  tagPrefix: v # so that tags are "v1.0", "v2.3.4"
  commitMessagePostfix: '[ci skip]' # when shipkit commits, this postfix can have ci skip it preferably
  # git config so it shows the user in the commits
  config:
    user: BuildBot
    email: <9cibot@9ci.com>
  releasable:
    branchRegex: 'master|release/.+'
    diff: # gets set to either travisDiff or circleDiff depending on autodetection of CI, can manually set this for local builds and testing
    circleDiff: 'git diff --name-only $(echo "$CIRCLE_COMPARE_URL" | rev | cut -d/ -f1 | rev)'
    travisDiff: 'git diff --name-only $TRAVIS_COMMIT_RANGE' # for Travis no parsing env var is needed.
    #grepDocs: ${config.git.releasable.diff +  ' | grep -E xxx'}
    grepDocs: ${config.git.releasable.circleDiff +  ' | grep -E (README\\.md|mkdocs\\.yml|docs/)' }
    grepRelease: ${config.git.releasable.diff +  ' | grep --invert-match -E (README\\.md|mkdocs\\.yml|docs/|src/examples/|src/test/)' }

project:
  fullName: # REQUIRED (example: yakworks/gradle-plugins) if none specified then will try to find from git config --get remote.origin.url
  owner: ${config.project.fullName.split('/')[0]} # example: yakworks
  repo: ${config.project.fullName.split('/')[1]} # example: gradle-plugins
  repoUrl: &GithubUrl ${'https://github.com/' + config.project.fullName}
  issuesUrl: &IssuesUrl ${config.project.repoUrl + '/issues'}
  #DO NOT set and checkin your token in yml here. Use a env var or gradle.properties
  writeAuthToken: '${System.getenv("GRGIT_USER") ?: System.getenv("GH_WRITE_TOKEN") ?: project.findProperty("gitHubToken")}'
  readOnlyAuthToken: '${System.getenv("GRGIT_USER") ?: System.getenv("GH_WRITE_TOKEN") ?: project.findProperty("gitHubToken") ?: "e7fe8fcdd6ffed5c38498c4c79b2a68e6f6ed1bb"}'

team:
  # keys here should be github user and name should match github name.
  developers: # REQUIRED List in form githubUser: Full Name ex: ['basejump: Joshua Burnett', 'jimbob: Jim Bob']
  contributors: # Other contribs , List same format as developers
  ignoredContributors: ['9cibot'] # list of names or logins to ignore, mostly for changlog. good for robot/CI user's commits when build/deploying

releaseNotes:
  file: docs/release-notes.md

maven:
  user: '${props.findAny("MAVEN_REPO_USER")}' # see notes above about env variables like this
  key: '${props.findAny("MAVEN_REPO_KEY")}'
  publishUrl: # NOT normally set in config.yml. this plugin will assign it either repoUrl or snapshotUrl depending on whether snapshot is true in version.properties
  repoUrl: 'http://repo.9ci.com/grails-plugins'
  snapshotUrl:

#spotless helps keep your code clean and spotless.
spotless:
  enabled: true
  # default license header file to use
  licenseHeader: |
    ${'/*\n' +
    '* Copyright \$YEAR ' + config.author + ' - Licensed under the Apache License, Version 2.0 (the "License")\n' +
    '* You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0\n' +
    '*/'
    }
  groovyTests:
    indentWithSpaces: 4
    trimTrailingWhitespace: true
    endWithNewline: true
    includes:
      - 'src/test/groovy/**/*.groovy'
      - 'src/integration-test/groovy/**/*.groovy'
  groovy:
    # licenseHeaderFile: # or you specify the file name of header file to use
    licenseHeader: $config.spotless.licenseHeader
    indentWithSpaces: 4
    trimTrailingWhitespace: true
    endWithNewline: true
    importOrder: ['java', 'groovy', 'org', '', 'static ']
    includes:
      - 'src/main/groovy/**/*.groovy'
      - 'grails-app/**/*.groovy'
    excludes:
      - '**/*.java'
      - '**/conf/**/*.groovy'
      # - 'grails-app/init/**/*.groovy'
  # groovyGradle:
  #   indentWithSpaces: 2
  #   trimTrailingWhitespace: true
  #   endWithNewline: true
  #   includes:
  #     - '**/*.gradle'
  #     - 'build.gradle'
  #     - 'gradle/*.gradle'

codenarc:
  toolVersion: 2.2.0
  config: prj.yakworks.getCodenarcRuleSet()
  reportFormat: 'html'
  maxPriority1Violations: 0
  maxPriority2Violations: 2
  maxPriority3Violations: 4
  main:
    enabled: true
    ignoreFailures: false
    excludes: # make this a list of excludes is wanted
  test:
    enabled: false # if false will exclude all files by adding a exclude: '**/*', runs much faster with lots of tests
    ignoreFailures: true
    excludes:
  integrationTest:
    enabled: false # if false will exclude all files by adding a exclude: '**/*', runs much faster with lots of tests
    ignoreFailures: true
    excludes:
# the mkdocs engine
docs:
  enabled: true
